services:
  frontend:
    #build:
    # context: .
    # dockerfile: Dockerfile
    image: registry.nguyenanhtsc.com/nguyen_anh_est/school_enrollment_fe:latest
    container_name: school_enrollment_fe
    restart: unless-stopped
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
      NUXT_PUBLIC_BASE_URL: https://apitest-tstt.clcgiangvo.edu.vn
      NUXT_ENCRYPTION_KEY: key-32-chars-123456
    ports:
      - "3000:3000"
